//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kurier_projekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaneSet
    {
        public int Id_klienta { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public System.DateTime Data_urodzenia { get; set; }
        public string Adres { get; set; }
        public string Kod_pocztowy { get; set; }
    }
}
