//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kurier_projekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GabarytySet
    {
        public int Gabaryt { get; set; }
        public int Wysokosc { get; set; }
        public int Dlugosc { get; set; }
        public int Szerokosc { get; set; }
        public int Cena { get; set; }
    }
}
