//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kurier_projekt.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IndywidualniEntities : DbContext
    {
        public IndywidualniEntities()
            : base("name=IndywidualniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DaneSet> DaneSet { get; set; }
        public virtual DbSet<GabarytySet> GabarytySet { get; set; }
        public virtual DbSet<ZamowieniaSet> ZamowieniaSet { get; set; }
    }
}
