//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kurier_projekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przesyłki
    {
        public int Id_Przesylki { get; set; }
        public string Nadawca { get; set; }
        public string Odbiorca { get; set; }
        public System.DateTime Data_nadania { get; set; }
        public string Adres_nadawcy { get; set; }
        public string Adres_odbiorcy { get; set; }
        public int Id_Kurier { get; set; }
    }
}
