//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kurier_projekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZamowieniaSet
    {
        public int Id_zamowienia { get; set; }
        public int Id_klienta { get; set; }
        public string Gabaryt { get; set; }
        public int Ilosc_przesylek { get; set; }
    }
}
